### ISSUE TITLE
htsparse.c:702]: (style) Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [xroche/httrack#109]
Source code is

  if ((p = strfield(html, "</html") != 0)) {

Suggest new code

  if ((p = strfield(html, "</html")) != 0) {

**Comment by xroche** [comment]
Humm, fortunately AFAICS it still does what it needs to: strfield() != 0 will yield 1 when the tag is found, and 0 if not found. Therefore, p will be 1 when the tag is found, which is what we want, for the "if (p != 0) {" test later. Changed in db336d2304900463d2dea4e42cea18aff3b35a28 anyway :)
