### ISSUE TITLE
No user option for cache size

### ISSUE THREAD

**Issue by mpheyse** [xroche/httrack#111]
I'm getting log entries for files re-downloaded due to lack of cache.  I have the "include all files in cache" option off so its only caching html files.  But there is no option to increase the cache size.

The current size of just HTML (and html.tmp) files is only 157MB  so my cache should only that big (or slightly smaller)

**Comment by xroche** [comment]
HTTRack caches everything, but the issue you are having is that the site probably does not fulfill update requests
