### ISSUE TITLE
164GB File ~/hts-nohup.out

### ISSUE THREAD

**Issue by ElectricPrism** [xroche/httrack#119]
It would seem HTTrack for some reason created a 164GB file, I dont know if this is a log, or what but it seems like the kind of problem that really needs some looking into.

I'm running HTTrack from Arch Linux Official Repository
community/httrack 3.48.22-2

**Comment by xroche** [comment]
You most probably used ^Z (control-Z) to pass httrack in background, and it created a log file, while continuing to capture whatever you were mirrorring.
