### ISSUE TITLE
httrack catchurl binds IPv6 only

### ISSUE THREAD

**Issue by gj12** [xroche/httrack#126]
Hi,

I'm using httrack under linux. If I try the --catchurl parameter, then httrack binds a proxy, but only to IPv6, this is useless if you have domains without IPv6 support.

```
httrack  --catchurl
Okay, temporary proxy installed.
Set your browser's preferences to:

        Proxy's address:        xxxx:xxxx:131:2365::2
        Proxy's port:   8080
```

**Comment by gj12** [comment]
It looks like that the gethostname returns the host from /etc/hostname and not localhost. And hts_dns_resolve_nocache always returns the IPv6 entry first.

**Comment by xroche** [comment]
I don't see any issue here - the proxy is bound to the local IP declared in the machine configuration (gethostname() is supposed to return the machine's address). You may use -@4 to force IPv4 resolution though.

**Comment by gj12** [comment]
The machine has 2 interfaces. The first has 1 IPv4 address and 2 IPv6. I don't know why this address is used...

Thank you for the tip with -@4 :)
