### ISSUE TITLE
Using HTTrack with Onion sites - Windows

### ISSUE THREAD

**Issue by Zekken01** [xroche/httrack#129]
Is there currently any way to use HTTrack with .onion sites? There are currently a few that i would like to save for offline use but I don't know of any other way to use save them.

**Comment by Imparium** [comment]
You can use Tor [as a proxy](https://www.httrack.com/html/step9_opt7.html)

**Comment by brodycas3** [comment]
How do I do that? What settings do I use.

**Comment by J-R-X** [comment]
Use proxy setting as 127.0.0.1:9150 while tor browser is running. Should work.
