### ISSUE TITLE
Unable to mirror a online? site. - Windows

### ISSUE THREAD

**Issue by brodycas3** [xroche/httrack#130]
I've found a site I'm trying to mirror and HTTrack is saying 
```
---------------------------
WinHTTrack Website Copier
---------------------------
* * MIRROR ERROR! * *

HTTrack has detected that the current mirror is empty. If it was an update, the previous mirror has been restored.

Reason: the first page(s) either could not be found, or a connection problem occurred.

=> Ensure that the website still exists, and/or check your proxy settings! <=
---------------------------
OK   
---------------------------
```

The site is using CloudFlares Always Online thing. so it is online?
![image](https://cloud.githubusercontent.com/assets/19770864/24558705/148c8abc-160a-11e7-94f4-cf42386124df.png)
I feel that the site may never come back online and wish to archive it.

NSFW> shadbase.com <NSFW

**Comment by xroche** [comment]
Please use forum.httrack.com for user-related issues
