### ISSUE TITLE
How to login into a website?

### ISSUE THREAD

**Issue by trusktr** [xroche/httrack#138]
In copying `famous.org` with `-n -B`, I see it is downloading some stuff like

```
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fatom%2Fatom%2Fpull%2Fnew%2Fmb-side-by-side-windows-installer
```

Maybe those parts won't work right, since it appears I was redirected to the Github login screen?

How would I log in?

**Comment by XP1** [comment]
You have to export your cookies from your browser to the `cookies.txt` file.

http://httrack.kauler.com/help/Cookies

**Comment by slrslr** [comment]
That cookies.txt file may be obtained using https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/ and belong to the root folder of the httrack project. Also htttrack should be set to same User-Agent as your web browser where you have logged-in to the site.
