### ISSUE TITLE
Confirm if this app is still under active development

### ISSUE THREAD

**Issue by CollinChaffin** [xroche/httrack#149]
Other than the basic updating of the years/dates I don't see much code improvement/dev for years.

For instance, the "capture URL" does not and HAS NOT worked properly for YEARS, and in fact now insists on opening proxy listener on IPv6 that it then never actually has the code to respond to properly - rendering that, like many other, features just not working at all that really need development cycles to mitigate.

I also see many open issues not even initially replied to dating back years and also several unanswered pull requests for proposed fixes for some of the many bugs, so I am opening this issue in hopes the primary author will confirm whether he is still able to dedicate any significant time into active development, or whether we are better off forking and starting our own branch.

**Comment by xroche** [comment]
The code is mostly in maintenance mode, but I do not currently have the time bandwidth to develp new features.
