### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by annajiat** [xroche/httrack#160]
From https://www.httrack.com/page/2/

In the row, "We recommend:",
the link to "httrack_x64-3.49.2.exe"

https://download.httrack.com/cserv.php3?File=httrack_x64.exe
results in

Not Found

The requested URL /cserv.php3 was not found on this server.

Apache/2.4 Server at download.httrack.com Port 443

**Comment by xroche** [comment]
Ah, problem spotted in HTTPS, thank you!
