### ISSUE TITLE
Assets from minified CSS not downloaded

### ISSUE THREAD

**Issue by joshas** [xroche/httrack#169]
Background images from minified CSS were not downloaded. In minified CSS they are stored like this:
> background:url(../images/logo/main.svg) no-repeat;
Same for webfonts declared in CSS.

**Comment by marcstern** [comment]
As most of modern web sites are now minified, this is a major problem

**Comment by marcstern** [comment]
In htsparse.c, we have on line 1348:
```
                      if (!nc && (nc = strfield(html, "url")) && (!isalnum(*(html - 1))) && *(html - 1) != '_') {  // url(url)
                        expected = '('; // parenthèse
                        expected_end = ")";     // fin: parenthèse
                        can_avoid_quotes = 1;
                        quotes_replacement = ')';
                      }

```
It's supposed to be supported !?!
Is it really a known bug unsolved for 4 years?

**Comment by foxtacles** [comment]
I'm experiencing the same issue - the parser does find and download the *first* asset it can find in a minified CSS, but then stops. I've done some testing, and the only way to fix this it seems is to place at least one line break character between each asset URL.

Effectively that means working with minified CSS (and probably other files falling under the "javascript" parser code path) isn't possible right now. A minimal reproducible example is for instance:

`.div{background:url(http://www.domain.com/quote-left.png) left no-repeat}.div2{background:url(http://www.domain.com/quote-right.png) left no-repeat}`

It will get the first image, but not the second. This however works fine:

```
`.div{background:url(http://www.domain.com/quote-left.png) left no-repeat}
.div2{background:url(http://www.domain.com/quote-right.png) left no-repeat}`
```
