### ISSUE TITLE
Would it be a ridiculous idea to download "https" website on your local computer, using  both httrack and git

### ISSUE THREAD

**Issue by corriedtoppin** [xroche/httrack#212]
Hello Github community.

first to begin. It may seems I have no understanding with any coding or download application experience. Then again. It may look like I am here to wasted other people time... I have no clue with coding, however I know what I am looking for, if you all are willing to help me...

I am trying to download a website using my username and password on my local computer, using "httrack"
here is the site: "https://app.pushbuttonautomarketer.com/site/login.phtml"

By reading other forums. I tried their suggestions by coping and pasting the information into httrack
#1 Copying and pasting URL, Username & Password.. also
#2 Coping and pasting codes from inspector elements:  User-Agent and Cookie.

None of the above worked. So I did some more digging. Only to discovered that "httrack" can not downlown "https" websites.
Here is the links below, which point me to here. I still have a negative feeling that it can not be done. BUT if it could.

You all would get a lot of views in this forum relating to the same...

What do you all suggest I do to move on the next step?

Thanks in advance

Cheers

https://forum.httrack.com/readmsg/39088/8190/index.html
https://hub.docker.com/r/automaticgiant/httrack-git
http://www.httrack.com/page/2/en/index.html
https://desktop.github.com/

**Comment by grv87** [comment]
1. Git have nothing to do with downloading websites over https. Yes, you could say that git is able to *download* git repositores. But repositories per se are not websites observable with browser.
    If you are refering to [https://hub.docker.com/r/automaticgiant/httrack-git](httrack-git), then it's just the name. It has no git inside.
    GitHub Desktop would not help you to download that website either (although, you probably can comment to this issue from there).

2. Looking at https://app.pushbuttonautomarketer.com/ I think it's most probably built on some AJAX technology where hyperlinks are generated by JavaScripts. You could check whether it's a real hyperlink with tooltip or status bar. For example, this is a real hyperlink:
    
    ![image](https://user-images.githubusercontent.com/2035596/134273582-e53c1bff-2bae-4597-82fe-22ec60978ad6.png)

    Generated hyperlinks are either empty or start with `javascript:`.

    HTTrack can download real hyperlinks only but not generated.

    You could probably have more success clipping specific pages of your website to OneNote or another clipper of your choice.

3. WinHTTrack is able to download websites over https.
    If it's really a problem with https, it's a problem with that specific website.

I have some other ideas that could help, but let's check out these ones for now.

**Comment by grv87** [comment]
@corriedtoppin, also note that https://hub.docker.com/r/automaticgiant/httrack-git provides HTTrack version 3.48-24 whereas the latest is 3.49-2.
