### ISSUE TITLE
Please Don't forget us! REVIVE THIS PROJECT!!! No serious development since 2017!!! 

### ISSUE THREAD

**Issue by alixsep** [xroche/httrack#224]
Hi.
Me along side with countless people want more developmet for httrack. Please work on the issues of this repo. Please redesign the web client the UI is awful. Please do these, we love this tool.

Clear as the title says, no more description needed. Thanks for the amazing tool ❤

Regards,
Alixsep

**Comment by mitchcapper** [comment]
There is a huge amount of activity around this tool and sadly as the web evolves so must archive tools.   I have put together a fork with many of the PR here and some other updates at https://github.com/mitchcapper/httrack until someone proper can take over maintenance and future development.
