### ISSUE TITLE
Poor UI/UX of the Website & Application

### ISSUE THREAD

**Issue by Raeskaa** [xroche/httrack#231]
I've been using [httrack](https://www.httrack.com/) for a few weeks now, I have noticed that the Website and the application itself have a very poor UI and are really not easy to use for each and every one. I would like to work as a UI/UX designer and redesign the whole system and also the official website. I just want to make sure that the design can be implemented so that the work doesn't go in vain.

## Website UI

![image](https://user-images.githubusercontent.com/84667136/179363268-4f3a5f50-616d-4188-8391-b88b6713d696.png)

## Application UI

![image](https://user-images.githubusercontent.com/84667136/179363261-fae158c9-510a-4b7f-92df-e6ed760d9b81.png)

Some Pros of having a better design would be

- It aids your search engine optimization (SEO) strategy so our website will pop up whenever someone searches ["How can I download the whole website"](https://www.google.com/search?q=How+can+I+download+the+whole+website&rlz=1C1CHBF_enIN923IN923&oq=How+can+I+download+the+whole+website&aqs=chrome..69i57.176j0j4&sourceid=chrome&ie=UTF-8) (PS - I got to know about httrack on [StackOverflow](https://superuser.com/questions/14403/how-can-i-download-an-entire-website#:~:text=390,Happy%20hunting!) )
- Reduce troubleshooting
- The increased trust of our users. Sites that are poorly designed are not credible or trustworthy to users and mostly they will quit early.
- Easy to use 
- Accessible to all ( The interface looks too much techy and not very clear with people who are not well versed with how to use a computer/Laptop  )

@xroche @JackDanger @glogiotatidis @cicku @gpunktschmitz @e-ht

**Comment by mitchcapper** [comment]
@Raeskaa I have been going through all the updates to get them applied for the project for an updated binary and code base at: https://github.com/mitchcapper/httrack  .  The current UI is written in MFC and quite dated.  I was debating previously a .NET update for it (something like Uno is even cross plat) but one could go the other route of improving the web version and making an electron app.   If you are up for putting together a new UI though I am sure it would be appreciated by everyone. 

As for the website clearly there is still quiet a good amount of activity in the forum.   I think eventually an 'official' unofficial fork may be required with a slightly different name to avoid confusion.  I am not really looking to steward such a larger project, mainly just due some maintenance and upkeep until someone else can.

I have a few other features to add to make it work with more modern websites, and maybe setup some CI actions to auto generate builds on commits.

**Comment by vitacell** [comment]
> @Raeskaa I have been going through all the updates to get them applied for the project for an updated binary and code base at: https://github.com/mitchcapper/httrack . The current UI is written in MFC and quite dated. I was debating previously a .NET update for it (something like Uno is even cross plat) but one could go the other route of improving the web version and making an electron app. If you are up for putting together a new UI though I am sure it would be appreciated by everyone.
> 
> As for the website clearly there is still quiet a good amount of activity in the forum. I think eventually an 'official' unofficial fork may be required with a slightly different name to avoid confusion. I am not really looking to steward such a larger project, mainly just due some maintenance and upkeep until someone else can.
> 
> I have a few other features to add to make it work with more modern websites, and maybe setup some CI actions to auto generate builds on commits.

Most modern GUIs are bloatware. Electron app are you seriously? It only makes things worse. And well, hope httrack stays far from .NET.

**Comment by mitchcapper** [comment]
> Most modern web GUIs are bloatware. Electron app are you seriously? It only makes things worse. And well, hope httrack stays far from .NET.
> It could be fine if it doesn't substitute the old stuff, and httrack doesn't depend on the new UI stuff.

I am not one to build electron apps, but merely was pointing to the fact it could easily wrap the web interface if improved.    Without a doubt you can have decent more resource usage with .NET or electron but never has the UI served as more than just a CLI builder + progress monitor for httrack.   So the UI overhead would be negligible for the use case.

I have not worked to build a UI but have been focusing on refining the MFC app and standardizing the CLI args so there is just one unified set of configuration rather than separate config for the UI vs httrack.
