### ISSUE TITLE
It can't copy this site.

### ISSUE THREAD

**Issue by Smurfboi007** [xroche/httrack#232]
Hi!

(I am using the latest version from the website.) I have been trying to copy this site for hours now. It is this: https://app.digiexam.com/app#/login

This is how it should look:
![2022-09-09 20_22_32-E-post](https://user-images.githubusercontent.com/68959201/189418511-55cfe979-c904-4026-9d48-107dd3e30c10.png)

This is how it looks:
![2022-09-09 20_25_29-194 26 192 125 - Fjärrskrivbordsanslutning](https://user-images.githubusercontent.com/68959201/189419000-a584114c-06de-423b-9671-2788d7424e63.png)

This is the error log: https://pastebin.com/0XVQ1iz2

Any ideas why it doesn't save the login boxes etc?

**Comment by xroche** [comment]
Some websites need login/cookie to be properly handled, and use of HTML5 or JS can make the mirroring virtually impossible.

Note: not a bug in httrack per so, but more a limitation.
