### ISSUE TITLE
Installer issue -

### ISSUE THREAD

**Issue by bovirus** [xroche/httrack#239]
@xroche 

The instalelr is mono language.
Could nbe multilanguage.

In Windows installer there are some issues regarding icon and program name and author.

![image](https://user-images.githubusercontent.com/1262554/209443068-cb8b5c15-7537-4b5e-ab70-be99479efb6f.png)

I can help with installer script.

Thanks.

**Comment by Neustradamus** [comment]
I confirm this icon problem.

There is no Windows installer source...

**Comment by bovirus** [comment]
@Neustradamus 

You can find here Windows installer

http://www.httrack.com/page/2/en/index.html

The installer script exist
