### ISSUE TITLE
Suppress root warning

### ISSUE THREAD

**Issue by marcstern** [xroche/httrack#241]
When you voluntary schedule a script as root, httrack gives each time a warning that pollutes the logs:
> WARNING! You are running this program as root!
> It might be a good idea to run as a different user

Could we add an option to suppress this?
That would enhance the readability and allow an easier detection of real warnings in the log (with grep f.i.).

**Comment by xroche** [comment]
Running as root is extremely dangerous, and ideally you should use `su` to downgrade the rights of the program.
