### ISSUE TITLE
[3.49.4] ./configure: line 13997: gl_VISIBILITY: command not found

### ISSUE THREAD

**Issue by hartwork** [xroche/httrack#245]
Hi @xroche,

I saw this while running vanilla `./configure` of 3.49.4:

```console
# wget https://github.com/xroche/httrack/archive/refs/tags/3.49.4.tar.gz
# tar xf 3.49.4.tar.gz
# cd httrack-3.49.4/
# ./configure
[..]
checking whether C compiler accepts -rdynamic... yes
./configure: line 13997: gl_VISIBILITY: command not found
checking size of long... 8
[..]
```

This is from a seemingly stray "gl_VISIBILITY" in file `configure.ac` — can it be removed?

Best, Sebastian

**Comment by xroche** [comment]
Seems that visibility.m4 is missing on gentoo; same issue apparently here: https://github.com/linuxmint/muffin/issues/570
I'm looking for a workaround.

**Comment by hartwork** [comment]
@xroche thanks for the fix! I think there's a misunderstanding here, nevertheless. I was primarily talking about the configure script that is currently in Git, not what you would get after running autoreconf locally. I personally believe these generated files should be removed from the Git because they go out of sync to easily. The alternative would be to add CI that goes red whenever they go out of sync. Let me know if you you welcome help on any of these approaches.
