### ISSUE TITLE
Implicit function declarations in configure logs

### ISSUE THREAD

**Issue by hartwork** [xroche/httrack#250]
Hi!

This QA issue was brought to my attention at https://bugs.gentoo.org/898834:
```
 * QA Notice: Found the following implicit function declarations in configure logs:
 *   /var/tmp/portage/www-client/httrack-3.49.4-r1/work/httrack-3.49.4/config.log:985 - strcmp
 *   /var/tmp/portage/www-client/httrack-3.49.4-r1/work/httrack-3.49.4/config.log:992 - exit
 *   /var/tmp/portage/www-client/httrack-3.49.4-r1/work/httrack-3.49.4/config.log:1026 - strcmp
 *   /var/tmp/portage/www-client/httrack-3.49.4-r1/work/httrack-3.49.4/config.log:1033 - exit
 * Check that no features were accidentally disabled.
 * See https://wiki.gentoo.org/wiki/Modern_C_porting.
```
So there is a risk that e.g. with Clang 16 compilation results will not be as intended/expected.
I do not see direct use of of `strcmp` or `exit` in [`configure.ac`](https://github.com/xroche/httrack/blob/master/configure.ac) so this is likely from the m4 files that httrack relies upon. Will need a closer look, I want to start with making the issue known.

Best, Sebastian

**Comment by xroche** [comment]
Fixed in 940bc759c9a26f70e75dc2af7ddbdeb6d72a3106
