### ISSUE TITLE
The splash screen only loads

### ISSUE THREAD

**Issue by darshanaalwis** [xroche/httrack#260]
**After editing the downloaded file and opening it, the splash screen only loads. How to fix it?**
![Screenshot 2023-09-10 142635](https://github.com/xroche/httrack/assets/144589631/6532ccf9-ef5f-4bc6-a021-1bfe5503cf4b)

**Comment by darshanaalwis** [comment]
fixed

**Comment by gamebeaker** [comment]
@darshanaalwis would be nice if you can elaborate how you fixed it so that people with the same problem know the fix.

**Comment by darshanaalwis** [comment]
@gamebeaker updated✅
