### ISSUE TITLE
Can you please update the download links for 3.49.4, i am having issues with the current version

### ISSUE THREAD

**Issue by bogasamai** [xroche/httrack#261]
On the current version, you can't add a large header. It is a problem for me since the cookie in the header is very large and so i can't even download any websites because of it

**Comment by hongfeiyang** [comment]
Same issue

**Comment by hongfeiyang** [comment]
After reading instructions in INSTALL I figured it out, so `configure` basically figures out the prerequisites and libraries this program needs for it to be compiled successfully, if you take a look at the `config.log` file generated after you run `./configure` you will see what actually went wrong, in your case, it is the SSL_CTX_new not available issue, which is the same issue I had. I was using an apple silicon Mac and the latest openssl library installed via home is `openssl@3` and its head files are under `opt/homebrew/opt/xxxxx`. This is different to Intel Macs therefore you need to make sure the compiler can see these openssl header files. Therefore adding

```
export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"  
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
```

will make sure your compiler can include your homebrew openssl libraries correctly
