### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by ciu82** [xroche/httrack#262]
Hello,
and sorry for my English :-)

I downloaded my website, but only the downloaded home page is ok, the others page appears like the one I attach.

Can anyone help me, please?

![a](https://github.com/xroche/httrack/assets/146256130/b6c8ad8c-b572-46a2-a7e6-aa016b57e88c)

**Comment by gamebeaker** [comment]
@ciu82 i need more information can you upload hts-cache->doit.log and hts-log.txt?
What is the URL and your settings for httrack?

**Comment by ciu82** [comment]
Hello,

thank you so much but now it seems ok!!!

 

 

Da: gamebeaker ***@***.***> 
Inviato: giovedì 28 settembre 2023 13:08
A: xroche/httrack ***@***.***>
Cc: ciu82 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [xroche/httrack] download issue (Issue #262)

 

@ciu82 <https://github.com/ciu82>  i need more information can you upload hts-cache->doit.log and hts-log.txt?
What is the URL and your settings for httrack?
