### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [xroche/httrack#268]
Dear @xroche,

It is time to create a new release build?

The latest is very very old: "Version 3.49-2 (20/05/2017)":
- https://www.httrack.com/

"2017-05-20": More 6 years, 6 months.

And please update the date with international ISO format too.

Thanks in advance.

**Comment by Neustradamus** [comment]
@xroche: Have you received my email?

**Comment by hongfeiyang** [comment]
It is not the Author's obligation to provide you with this piece of software. Also I don't know if anyone told you before that asking people like this is not very polite.
And if you really need this software you can build it yourself. Everything you need to know to build the program yourself has already been written down in the INSTALL file.

**Comment by Neustradamus** [comment]
@hongfeiyang: Thanks for your comment :)
I am very polite.
I think it is time to request a new build, the latest is very old and not secure badly, there are CVEs.
Soon 7 years without CVE fixes.

**Comment by xroche** [comment]
A new minor maintenance release was released in 70d43d42b5bef9057b5387c0d80556ecb9045779 (3.49.5)

**Comment by xroche** [comment]
A new minor maintenance release was released in 70d43d42b5bef9057b5387c0d80556ecb9045779 (3.49.5)

**Comment by Neustradamus** [comment]
@xroche: I do not see new release build:
- https://www.httrack.com/

It is possible to have your good e-mail address?
I think that there is a problem with your mailbox.

Can you help me?

Linked to:
- https://github.com/xroche/httrack/issues/243
- https://github.com/xroche/httrack/issues/249

**Comment by Neustradamus** [comment]
@xroche: It is possible to create Windows 3.49.5 release builds?
The current is very old and is 3.49-2 (2017-05-20), more than 7 years old.

**Comment by Neustradamus** [comment]
@xroche: Have you progressed on it?
