### ISSUE TITLE
Minizip update request

### ISSUE THREAD

**Issue by Neustradamus** [xroche/httrack#272]
Dear @xroche,

There is Minizip here:
- https://github.com/xroche/httrack/tree/master/src/minizip

It will be nice to have compatibility with current Minizip (included in zlib 1.3.1) and Minizip NG?
- https://github.com/madler/zlib/tree/master/contrib/minizip
- https://github.com/madler/zlib/tree/develop/contrib/minizip
- https://github.com/zlib-ng/minizip-ng

zlib 1.3.1 has 2 recent CVE fixes for Minizip.

cc: @jayaddison.

Linked to:
- https://github.com/xroche/httrack/issues/240
- https://github.com/xroche/httrack/pull/265

**Comment by xroche** [comment]
Fixed in b625cfe82ab34374f3cad7ef3941a6c001fc4876

I'll make a new release soon. Thanks for reaching out!

**Comment by jayaddison** [comment]
> Fixed in [b625cfe](https://github.com/xroche/httrack/commit/b625cfe82ab34374f3cad7ef3941a6c001fc4876)
> 
> I'll make a new release soon. Thanks for reaching out!

Perfect: FWIW, the only difference between the contents of b625cfe82ab34374f3cad7ef3941a6c001fc4876 and a local branch I'd prepared to apply the same changes was the timestamping (not the patch contents) in the `zip.c.diff` file.
