### ISSUE TITLE
github access

### ISSUE THREAD

**Issue by rahrah** [xroche/httrack#64]
Hi,

Downloading your repo from github is a problem for
anonymous users not using the ssh protocol.  When the submodule is downloaded,
git asks for a password.  

Would it be possible for you to use:
```
url = <https://github.com/xroche/coucal.git>
```
as the url instead of 
```
url = git@github.com:xroche/coucal.git
```
for the submodule url?

Thanks,

===Rich

**Comment by xroche** [comment]
Fixed thanks to [Pat Brisbin's blog](https://pbrisbin.com/posts/git_submodule_config/)
