### ISSUE TITLE
HTTrack in MS Windows can not handle path creation longer than 255 characters

### ISSUE THREAD

**Issue by FelixLeo** [xroche/httrack#68]
Dear Developers,
I just did notice that if the initial save location for site mirroring is long/deep enough and HTTrack starts to mirror a site with many sub-folders or long file names the resulting mirrored file names are truncated without any warnings or error messages at 255 char boundary. Would it be possible for you to modify your application and put a tick mark setting (lets say as it exists in  application TeraCopy MaxPathLimit=1 [0: Allow to create extra long paths (> 255 characters)]) when option enabled the application can read and create file names longer than 255 chars or if disabled to stay compatible with the 255 char boundary but when detected such condition to warn you  that file names are going to be truncated and to stop the download process and ask you to shorten the whole mirror save path and than restart downloading and in the log file to save info about what are the real file names and to what they were truncated if any such overflow happens, as the file contents are correct but later even manually we cant correct the names as we wouldn't know which file was what in case of similar names which were truncated.
Thanks.

**Comment by Desaroll** [comment]
As far as I know:

The 260 characters long path (256 if you count the "C:/" and the null character at the end of the string), is a Windows thing:
https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx

Even when it can be worked around with the official API, the File Explorer of Windows is not compatible with paths longer that 256 characters, and you would need use another file manager to work with those.

So, I guess the second work around is better.

(I'm just leaving the info here. I'm not a developer of httrack)

**Comment by xroche** [comment]
Normally 260-characters limit is enforced. Do you have cases where it fails to enforce this limit ?

See htsname.c:

`
  // enforce 260-character path limit before inserting destination path
  // note: 12 characters at least for WIN32, and 12 for ".99.delayed"
  // (MSDN) "When using an API to create a directory, the specified path
  // cannot be so long that you cannot append an 8.3 file name
  // (that is, the directory name cannot exceed MAX_PATH minus 12)."
#define HTS_MAX_PATH_LEN ( 260 - 12 - 12 )
#define MIN_LAST_SEG_RESERVE 12
#define MAX_LAST_SEG_RESERVE 24
#define MAX_SEG_LEN 48
`

**Comment by FelixLeo** [comment]
Hi there,
the problem is not with the initial check when it starts.
It can easily happen that I do start to save a site at the root folder for example at C:\
and during the download process httrack when getting deep in the sub-folders when it reaches the 256 boundary it will not give a warning or keep a list of what file it was not able to give it's full name it will simply cut off any characters of the original file names after the total 256 character length.
it will be something like this:
let say the original site file looks like this
\.......................\test.html after hitting the border the name will be saved until it. For example like this
C:\....................\te
When this happens if there is no other similar file name in the saved folder I can manually change the name to the correct ones after shortening the folder names for my self and correcting the folder htmls which httrack generates. But when you have on the original site "test1.html", "test2.html", "test3.html" will it overwrite it I don't know? Cause as the example above all would have been saved as "te" and perhaps only the last file will be there?
Thanks

**Comment by dealancer** [comment]
Same is true for Linux. I have cut of if path is longer then 237 characters. See https://github.com/xroche/httrack/issues/133

**Comment by grv87** [comment]
+1 for this.

Windows 10 is here for several years now, with path limits increased.
